# Generated by Django 2.2.3 on 2020-05-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20200502_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='elements_icons', verbose_name='иконка'),
        ),
    ]
