# Generated by Django 2.2.3 on 2020-05-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_auto_20200502_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='element_types',
            field=models.ManyToManyField(blank=True, related_name='pokemons', to='pokemon_entities.PokemonElementType', verbose_name='стихия'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons_entities', to='pokemon_entities.Pokemon', verbose_name='покемон'),
        ),
    ]
